# Generated by Django 6.0.4 on 2026-04-24 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_unit_price_booking_units_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('bank_transfer', 'Transferência bancária'), ('cash', 'Pagamento no local'), ('other', 'Outro')], max_length=30, verbose_name='Método de pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor pago')),
                ('platform_commission_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Comissão da plataforma (%)')),
                ('platform_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão MozGuest')),
                ('owner_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do proprietário')),
                ('transaction_reference', models.CharField(blank=True, max_length=150, verbose_name='Referência da transacção')),
                ('proof', models.ImageField(blank=True, null=True, upload_to='payments/', verbose_name='Comprovativo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('submitted', 'Comprovativo enviado'), ('confirmed', 'Confirmado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Estado')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas administrativas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado em')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='Reserva')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
