# Generated by Django 6.0.4 on 2026-06-05 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('initiated', 'Pagamento iniciado'), ('submitted', 'Comprovativo enviado'), ('confirmed', 'Confirmado'), ('rejected', 'Rejeitado'), ('failed', 'Falhado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('bank_transfer', 'Transferência bancária'), ('manual', 'Comprovativo manual'), ('other', 'Outro gateway')], max_length=30, verbose_name='Gateway')),
                ('status', models.CharField(choices=[('created', 'Criada'), ('initiated', 'Iniciada'), ('waiting_authorization', 'Aguardando autorização'), ('paid', 'Paga'), ('failed', 'Falhada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada'), ('refunded', 'Reembolsada')], default='created', max_length=30, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Número que vai autorizar o pagamento')),
                ('local_reference', models.CharField(blank=True, max_length=60, unique=True, verbose_name='Referência +258 Guest')),
                ('external_reference', models.CharField(blank=True, max_length=150, verbose_name='Referência do provedor')),
                ('checkout_url', models.URLField(blank=True, verbose_name='URL de checkout')),
                ('provider_response', models.TextField(blank=True, verbose_name='Resposta do provedor')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('callback_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Callback recebido em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado em')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Transacção de pagamento',
                'verbose_name_plural': 'Transacções de pagamento',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gateway', 'status'], name='payments_pa_gateway_186290_idx'), models.Index(fields=['local_reference'], name='payments_pa_local_r_2c898d_idx'), models.Index(fields=['external_reference'], name='payments_pa_externa_e4a306_idx')],
            },
        ),
    ]
