# Generated by ChatGPT on 2026-06-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_alter_payment_status_paymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor pago pelo cliente')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão +258 Guest')),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor líquido a pagar ao proprietário')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('scheduled', 'Agendada'), ('paid', 'Liquidada'), ('held', 'Retida'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado da liquidação')),
                ('method', models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('bank_transfer', 'Transferência bancária'), ('cash', 'Numerário'), ('other', 'Outro')], max_length=30, verbose_name='Método de liquidação')),
                ('payout_reference', models.CharField(blank=True, max_length=150, verbose_name='Referência de liquidação')),
                ('payout_phone', models.CharField(blank=True, max_length=30, verbose_name='Número de pagamento do proprietário')),
                ('payout_bank_details', models.TextField(blank=True, verbose_name='Dados bancários / observações de pagamento')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas administrativas')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Agendada para')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Liquidada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada em')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_payouts', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_payout', to='payments.payment', verbose_name='Pagamento do cliente')),
            ],
            options={
                'verbose_name': 'Liquidação ao proprietário',
                'verbose_name_plural': 'Liquidações aos proprietários',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_ow_status_f88d42_idx'), models.Index(fields=['owner', 'status'], name='payments_ow_owner_i_582650_idx'), models.Index(fields=['created_at'], name='payments_ow_created_881caf_idx')],
            },
        ),
    ]
