# Generated by Django 6.0.4 on 2026-04-25 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do plano')),
                ('plan_type', models.CharField(choices=[('free', 'Gratuito'), ('featured', 'Destaque'), ('premium', 'Premium')], default='free', max_length=30, verbose_name='Tipo')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço mensal')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Comissão (%)')),
                ('max_properties', models.PositiveIntegerField(default=1, verbose_name='Máximo de propriedades')),
                ('max_photos_per_property', models.PositiveIntegerField(default=10, verbose_name='Máximo de fotos por propriedade')),
                ('can_feature_properties', models.BooleanField(default=False, verbose_name='Pode destacar propriedades')),
                ('priority_support', models.BooleanField(default=False, verbose_name='Suporte prioritário')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Plano comercial',
                'verbose_name_plural': 'Planos comerciais',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='OwnerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('pending', 'Pendente'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('notes', models.TextField(blank=True, verbose_name='Notas administrativas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='monetization.commercialplan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Subscrição do proprietário',
                'verbose_name_plural': 'Subscrições dos proprietários',
                'ordering': ['-created_at'],
            },
        ),
    ]
