# Generated by Django 6.0.4 on 2026-06-05 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('property_approved', 'Propriedade aprovada'), ('property_rejected', 'Propriedade rejeitada'), ('property_featured', 'Destaque de propriedade alterado'), ('review_approved', 'Avaliação aprovada'), ('review_rejected', 'Avaliação rejeitada'), ('booking_accepted', 'Reserva aceite'), ('booking_rejected', 'Reserva rejeitada'), ('booking_cancelled', 'Reserva cancelada'), ('booking_completed', 'Reserva concluída'), ('payment_confirmed', 'Pagamento confirmado'), ('payment_rejected', 'Pagamento rejeitado'), ('payout_paid', 'Liquidação paga'), ('payout_held', 'Liquidação retida'), ('payout_synced', 'Liquidações sincronizadas'), ('owner_verified', 'Proprietário verificado'), ('owner_rejected', 'Verificação do proprietário rejeitada'), ('owner_suspended', 'Proprietário suspenso'), ('refund_reviewed', 'Cancelamento/reembolso revisto'), ('other', 'Outra acção')], default='other', max_length=50, verbose_name='Acção')),
                ('target_model', models.CharField(blank=True, max_length=120, verbose_name='Modelo alvo')),
                ('target_id', models.CharField(blank=True, max_length=80, verbose_name='ID alvo')),
                ('target_repr', models.CharField(blank=True, max_length=255, verbose_name='Descrição do alvo')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Navegador/Dispositivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest258_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador que executou')),
            ],
            options={
                'verbose_name': 'Registo de auditoria',
                'verbose_name_plural': 'Registos de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='dashboard_a_action_69ca82_idx'), models.Index(fields=['target_model', 'target_id'], name='dashboard_a_target__c80936_idx'), models.Index(fields=['actor', 'created_at'], name='dashboard_a_actor_i_5889c1_idx')],
            },
        ),
    ]
