# Generated by Django 6.0.4 on 2026-04-24 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='Nome comercial')),
                ('document_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Número do documento')),
                ('nuit', models.CharField(blank=True, max_length=50, verbose_name='NUIT')),
                ('payment_phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone para pagamentos')),
                ('verification_status', models.CharField(choices=[('pending', 'Pendente'), ('verified', 'Verificado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Estado de verificação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Perfil do Proprietário',
                'verbose_name_plural': 'Perfis dos Proprietários',
            },
        ),
    ]
