# Generated by Django 6.0.4 on 2026-06-05 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/owners/', verbose_name='Documento de identificação'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='nuit_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/owners/', verbose_name='Comprovativo de NUIT'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='ownership_proof',
            field=models.FileField(blank=True, null=True, upload_to='kyc/owners/', verbose_name='Comprovativo de titularidade/autorização do alojamento'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='payout_bank_details',
            field=models.TextField(blank=True, verbose_name='Dados bancários para liquidação'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='payout_emola_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número e-Mola para liquidação'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='payout_mpesa_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número M-Pesa para liquidação'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='Notas de verificação'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verificado em'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_owner_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Não verificado'), ('pending', 'Pendente'), ('in_review', 'Em análise'), ('verified', 'Verificado'), ('rejected', 'Rejeitado'), ('suspended', 'Suspenso')], default='unverified', max_length=20, verbose_name='Estado de verificação'),
        ),
    ]
