# Generated by Django 6.0.4 on 2026-04-25 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_availabilityblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('booking_problem', 'Problema com reserva'), ('payment_problem', 'Problema com pagamento'), ('property_problem', 'Problema com alojamento'), ('client_problem', 'Problema com cliente'), ('owner_problem', 'Problema com proprietário'), ('technical_problem', 'Problema técnico'), ('other', 'Outro')], default='other', max_length=40, verbose_name='Categoria')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_review', 'Em análise'), ('resolved', 'Resolvida'), ('rejected', 'Rejeitada')], default='open', max_length=20, verbose_name='Estado')),
                ('admin_response', models.TextField(blank=True, verbose_name='Resposta da administração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado em')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='bookings.booking', verbose_name='Reserva relacionada')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Reclamação/Suporte',
                'verbose_name_plural': 'Reclamações/Suporte',
                'ordering': ['-created_at'],
            },
        ),
    ]
