# Generated by Django 6.0.4 on 2026-04-24 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do estabelecimento')),
                ('property_type', models.CharField(choices=[('guest_house', 'Guest House'), ('room', 'Quarto'), ('apartment', 'Apartamento'), ('residence', 'Residência'), ('lodge', 'Pousada'), ('other', 'Outro')], max_length=50, verbose_name='Tipo de alojamento')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Província')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Distrito')),
                ('neighbourhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('address_reference', models.CharField(blank=True, max_length=255, verbose_name='Referência de localização')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('suspended', 'Suspenso')], default='pending', max_length=20, verbose_name='Estado')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Em destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do quarto/unidade')),
                ('room_type', models.CharField(choices=[('single', 'Quarto Individual'), ('double', 'Quarto de Casal'), ('suite', 'Suíte'), ('apartment', 'Apartamento'), ('studio', 'Estúdio'), ('house', 'Casa'), ('other', 'Outro')], max_length=50, verbose_name='Tipo de unidade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Capacidade de pessoas')),
                ('price_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço por hora')),
                ('price_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço por dia')),
                ('price_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço por noite')),
                ('price_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço mensal')),
                ('minimum_hours', models.PositiveIntegerField(default=1, verbose_name='Mínimo de horas')),
                ('has_private_bathroom', models.BooleanField(default=False, verbose_name='Casa de banho privativa')),
                ('has_ac', models.BooleanField(default=False, verbose_name='Ar condicionado')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Estacionamento')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Quarto/Unidade',
                'verbose_name_plural': 'Quartos/Unidades',
                'ordering': ['property', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagem principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property', verbose_name='Propriedade')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.room', verbose_name='Quarto/Unidade')),
            ],
            options={
                'verbose_name': 'Fotografia',
                'verbose_name_plural': 'Fotografias',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
    ]
