# Generated by Django 6.0.4 on 2026-04-25 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cleanliness_rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Limpeza'),
        ),
        migrations.AddField(
            model_name='review',
            name='comfort_rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Conforto'),
        ),
        migrations.AddField(
            model_name='review',
            name='location_rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='review',
            name='security_rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Segurança'),
        ),
        migrations.AddField(
            model_name='review',
            name='service_rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Atendimento'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado em'),
        ),
        migrations.AddField(
            model_name='review',
            name='value_rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Preço/qualidade'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Avaliação geral'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('property', 'user'), name='unique_review_per_user_property'),
        ),
    ]
