# Generated by Django 6.0.4 on 2026-04-24 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Nome do cliente')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Telefone do cliente')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do cliente')),
                ('booking_type', models.CharField(choices=[('hour', 'Por hora'), ('day', 'Por dia'), ('night', 'Por noite'), ('month', 'Mensal')], max_length=20, verbose_name='Tipo de reserva')),
                ('checkin_date', models.DateField(verbose_name='Data de entrada')),
                ('checkin_time', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('checkout_date', models.DateField(blank=True, null=True, verbose_name='Data de saída')),
                ('checkout_time', models.TimeField(blank=True, null=True, verbose_name='Hora de saída')),
                ('number_of_guests', models.PositiveIntegerField(default=1, verbose_name='Número de pessoas')),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor estimado')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceite'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada'), ('completed', 'Concluída')], default='pending', max_length=20, verbose_name='Estado')),
                ('client_notes', models.TextField(blank=True, verbose_name='Observações do cliente')),
                ('owner_notes', models.TextField(blank=True, verbose_name='Observações do proprietário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado em')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Cliente registado')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property', verbose_name='Propriedade')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.room', verbose_name='Quarto/Unidade')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
