# Generated by Django 6.0.4 on 2026-04-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço unitário'),
        ),
        migrations.AddField(
            model_name='booking',
            name='units_count',
            field=models.PositiveIntegerField(default=1, help_text='Horas, dias, noites ou meses calculados conforme o tipo de reserva.', verbose_name='Quantidade calculada'),
        ),
    ]
