# Generated by Django 6.0.4 on 2026-04-24 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_unit_price_booking_units_count'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Início do bloqueio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fim do bloqueio')),
                ('reason', models.CharField(choices=[('maintenance', 'Manutenção'), ('external_booking', 'Reserva externa'), ('owner_block', 'Bloqueio do proprietário'), ('other', 'Outro motivo')], default='owner_block', max_length=30, verbose_name='Motivo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='properties.room', verbose_name='Quarto/Unidade')),
            ],
            options={
                'verbose_name': 'Bloqueio de disponibilidade',
                'verbose_name_plural': 'Bloqueios de disponibilidade',
                'ordering': ['-start_datetime'],
            },
        ),
    ]
