# Generated by Django 6.0.4 on 2026-06-05 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_availabilityblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Motivo do cancelamento'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('client', 'Cliente'), ('owner', 'Proprietário'), ('admin', '+258 Guest'), ('system', 'Sistema')], max_length=20, verbose_name='Cancelada por'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de reembolso'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_notes',
            field=models.TextField(blank=True, verbose_name='Notas sobre reembolso/cancelamento'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=150, verbose_name='Referência de reembolso'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reembolso revisto em'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_booking_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Reembolso revisto por'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('not_applicable', 'Não aplicável'), ('pending_review', 'Em análise'), ('no_refund', 'Sem reembolso'), ('partial_refund', 'Reembolso parcial'), ('full_refund', 'Reembolso total'), ('refunded', 'Reembolsado')], default='not_applicable', max_length=30, verbose_name='Estado de reembolso'),
        ),
    ]
